# Generated by Django 4.2.3 on 2023-08-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('id_product', models.CharField(max_length=20)),
                ('amount_on_action', models.IntegerField(default=0)),
                ('amount_exists_on_time', models.IntegerField(default=0)),
                ('action_on_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
