# Generated by Django 4.2.3 on 2023-08-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_product_img'),
        ('Product', '0009_alter_product_img'),
    ]

    operations = [
    ]
